-- MySQL Script generated by MySQL Workbench
-- Sun Apr  4 13:51:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospital` (
  `idHospital` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Town` VARCHAR(45) NOT NULL,
  `Phone Number` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `idDoctor` INT NOT NULL,
  `Last Name` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Specialization` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone Number` DECIMAL(10) NOT NULL,
  `Hospital_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDoctor`, `Hospital_Name`),
  INDEX `fk_Doctor_Hospital1_idx` (`Hospital_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Hospital1`
    FOREIGN KEY (`Hospital_Name`)
    REFERENCES `mydb`.`Hospital` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`e-Government Center for Social Security (IDIKA)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`e-Government Center for Social Security (IDIKA)` (
  `ide-Government Center for Social Security (IDIKA)` INT NOT NULL,
  `Last Name` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `AMKA` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone Number` DECIMAL(10) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Date of Birth` DATE NOT NULL,
  `Age` INT NOT NULL,
  PRIMARY KEY (`AMKA`),
  UNIQUE INDEX `AMKA_UNIQUE` (`AMKA` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Phone Number_UNIQUE` (`Phone Number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `idPatiens` INT NOT NULL,
  `Last Name` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone Number` DECIMAL(10) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Medical History` VARCHAR(45) NOT NULL,
  `e-Government Center for Social Security (IDIKA)_AMKA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPatiens`, `e-Government Center for Social Security (IDIKA)_AMKA`),
  INDEX `fk_Patient_e-Government Center for Social Security (IDIKA)1_idx` (`e-Government Center for Social Security (IDIKA)_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_e-Government Center for Social Security (IDIKA)1`
    FOREIGN KEY (`e-Government Center for Social Security (IDIKA)_AMKA`)
    REFERENCES `mydb`.`e-Government Center for Social Security (IDIKA)` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COVID Unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COVID Unit` (
  `idCOVID` INT NOT NULL,
  `Total Room Numbers` INT NOT NULL,
  PRIMARY KEY (`idCOVID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hospitalization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hospitalization` (
  `idHospitalization` INT NOT NULL,
  `Unit` VARCHAR(45) NOT NULL,
  `Symptom` VARCHAR(45) NOT NULL,
  `Medication` VARCHAR(45) NOT NULL,
  `People who came in to contact with` VARCHAR(100) NULL,
  `COVID_idCOVID` INT NOT NULL,
  PRIMARY KEY (`idHospitalization`, `COVID_idCOVID`),
  INDEX `fk_Hospitalization_COVID1_idx` (`COVID_idCOVID` ASC) VISIBLE,
  CONSTRAINT `fk_Hospitalization_COVID1`
    FOREIGN KEY (`COVID_idCOVID`)
    REFERENCES `mydb`.`COVID Unit` (`idCOVID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COVID-19 Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COVID-19 Test` (
  `idCOVID-19 Test` INT NOT NULL,
  `Rapid` VARCHAR(45) NULL,
  `RT-PCR` VARCHAR(45) NULL,
  `Hospitalization_idHospitalization` INT NOT NULL,
  `Hospitalization_COVID_idCOVID` INT NOT NULL,
  PRIMARY KEY (`idCOVID-19 Test`, `Hospitalization_idHospitalization`, `Hospitalization_COVID_idCOVID`),
  INDEX `fk_COVID-19 Test_Hospitalization1_idx` (`Hospitalization_idHospitalization` ASC, `Hospitalization_COVID_idCOVID` ASC) VISIBLE,
  CONSTRAINT `fk_COVID-19 Test_Hospitalization1`
    FOREIGN KEY (`Hospitalization_idHospitalization` , `Hospitalization_COVID_idCOVID`)
    REFERENCES `mydb`.`Hospitalization` (`idHospitalization` , `COVID_idCOVID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical Centers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical Centers` (
  `idMedical Centers` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone Number` DECIMAL(10) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedical Centers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NO COVID Unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NO COVID Unit` (
  `idNO COVID` INT NOT NULL,
  PRIMARY KEY (`idNO COVID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Intensive Care Unit (ICU)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Intensive Care Unit (ICU)` (
  `idIntensive Care Unit (ICU)` INT NOT NULL,
  `Medical Specialisation` VARCHAR(45) NOT NULL,
  `Number of Beds` INT NOT NULL,
  `Number of Patients` INT NOT NULL,
  `NO COVID_idNO COVID` INT NOT NULL,
  `COVID_idCOVID` INT NOT NULL,
  `Hospital_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIntensive Care Unit (ICU)`, `NO COVID_idNO COVID`, `COVID_idCOVID`, `Hospital_Name`),
  INDEX `fk_Intensive Care Unit (ICU)_NO COVID1_idx` (`NO COVID_idNO COVID` ASC) VISIBLE,
  INDEX `fk_Intensive Care Unit (ICU)_COVID1_idx` (`COVID_idCOVID` ASC) VISIBLE,
  INDEX `fk_Intensive Care Unit (ICU)_Hospital1_idx` (`Hospital_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Intensive Care Unit (ICU)_NO COVID1`
    FOREIGN KEY (`NO COVID_idNO COVID`)
    REFERENCES `mydb`.`NO COVID Unit` (`idNO COVID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Intensive Care Unit (ICU)_COVID1`
    FOREIGN KEY (`COVID_idCOVID`)
    REFERENCES `mydb`.`COVID Unit` (`idCOVID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Intensive Care Unit (ICU)_Hospital1`
    FOREIGN KEY (`Hospital_Name`)
    REFERENCES `mydb`.`Hospital` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Examination` (
  `idExamination` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Definition` VARCHAR(90) NOT NULL,
  `Results` VARCHAR(45) NOT NULL,
  `Hospitalization_idHospitalization` INT NOT NULL,
  PRIMARY KEY (`idExamination`, `Hospitalization_idHospitalization`),
  INDEX `fk_Examination_Hospitalization1_idx` (`Hospitalization_idHospitalization` ASC) VISIBLE,
  CONSTRAINT `fk_Examination_Hospitalization1`
    FOREIGN KEY (`Hospitalization_idHospitalization`)
    REFERENCES `mydb`.`Hospitalization` (`idHospitalization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `idRoom` INT NOT NULL,
  `Number of Beds` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`National Public Health Organization (NPHO/EODY)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`National Public Health Organization (NPHO/EODY)` (
  `idNational Public Health Organization (NPHO/EODY)` INT NOT NULL,
  `Date of the check up` DATE NOT NULL,
  `Test Results` VARCHAR(45) NOT NULL,
  `e-Government Center for Social Security (IDIKA)_AMKA` VARCHAR(45) NOT NULL,
  `COVID-19 Test_idCOVID-19 Test` INT NOT NULL,
  PRIMARY KEY (`idNational Public Health Organization (NPHO/EODY)`),
  INDEX `fk_National Public Health Organization (NPHO/EODY)_e-Govern_idx` (`e-Government Center for Social Security (IDIKA)_AMKA` ASC) VISIBLE,
  INDEX `fk_National Public Health Organization (NPHO/EODY)_COVID-19_idx` (`COVID-19 Test_idCOVID-19 Test` ASC) VISIBLE,
  CONSTRAINT `fk_National Public Health Organization (NPHO/EODY)_e-Governme1`
    FOREIGN KEY (`e-Government Center for Social Security (IDIKA)_AMKA`)
    REFERENCES `mydb`.`e-Government Center for Social Security (IDIKA)` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_National Public Health Organization (NPHO/EODY)_COVID-19 T1`
    FOREIGN KEY (`COVID-19 Test_idCOVID-19 Test`)
    REFERENCES `mydb`.`COVID-19 Test` (`idCOVID-19 Test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccine Producing Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccine Producing Company` (
  `idVaccine Producing Company` INT NOT NULL,
  `Name of the company` VARCHAR(45) NOT NULL,
  `Phone Number` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Technology` VARCHAR(45) NOT NULL,
  `Storing Circumstances` VARCHAR(45) NOT NULL,
  `Amount of products per month` DECIMAL(10000) NOT NULL,
  PRIMARY KEY (`idVaccine Producing Company`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`European Medicines Agency (EMA)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`European Medicines Agency (EMA)` (
  `idEuropean Medicines Agency (EMA)` INT NOT NULL,
  PRIMARY KEY (`idEuropean Medicines Agency (EMA)`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccines` (
  `idVaccines` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Date of Production` DATE NOT NULL,
  `Quantity of Vaccines` VARCHAR(45) NOT NULL,
  `Destination Country` VARCHAR(45) NOT NULL,
  `Vaccine Producing Company_idVaccine Producing Company` INT NOT NULL,
  `Date of approval` DATE NULL,
  `Number of doses` INT NOT NULL,
  `Ema Code` VARCHAR(45) NULL,
  `European Medicines Agency (EMA)_idEuropean Medicines Agency (EMA)` INT NOT NULL,
  PRIMARY KEY (`idVaccines`, `Vaccine Producing Company_idVaccine Producing Company`, `European Medicines Agency (EMA)_idEuropean Medicines Agency (EMA)`),
  INDEX `fk_Vaccines_Vaccine Producing Company1_idx` (`Vaccine Producing Company_idVaccine Producing Company` ASC) VISIBLE,
  INDEX `fk_Vaccines_European Medicines Agency (EMA)1_idx` (`European Medicines Agency (EMA)_idEuropean Medicines Agency (EMA)` ASC) VISIBLE,
  CONSTRAINT `fk_Vaccines_Vaccine Producing Company1`
    FOREIGN KEY (`Vaccine Producing Company_idVaccine Producing Company`)
    REFERENCES `mydb`.`Vaccine Producing Company` (`idVaccine Producing Company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaccines_European Medicines Agency (EMA)1`
    FOREIGN KEY (`European Medicines Agency (EMA)_idEuropean Medicines Agency (EMA)`)
    REFERENCES `mydb`.`European Medicines Agency (EMA)` (`idEuropean Medicines Agency (EMA)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Storing Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Storing Company` (
  `idStoring Company` INT NOT NULL,
  `Storage Condistions` VARCHAR(45) NOT NULL,
  `Vaccine Center` VARCHAR(45) NOT NULL,
  `Vaccines_idVaccines` INT NOT NULL,
  `Vaccines_Vaccine Producing Company_idVaccine Producing Company` INT NOT NULL,
  `Vaccines_European Medicines Agency (EMA)_idEuropean Medicines Agency (EMA)` INT NOT NULL,
  PRIMARY KEY (`idStoring Company`, `Vaccines_idVaccines`, `Vaccines_Vaccine Producing Company_idVaccine Producing Company`, `Vaccines_European Medicines Agency (EMA)_idEuropean Medicines Agency (EMA)`),
  INDEX `fk_Storing Company_Vaccines1_idx` (`Vaccines_idVaccines` ASC, `Vaccines_Vaccine Producing Company_idVaccine Producing Company` ASC, `Vaccines_European Medicines Agency (EMA)_idEuropean Medicines Agency (EMA)` ASC) VISIBLE,
  CONSTRAINT `fk_Storing Company_Vaccines1`
    FOREIGN KEY (`Vaccines_idVaccines` , `Vaccines_Vaccine Producing Company_idVaccine Producing Company` , `Vaccines_European Medicines Agency (EMA)_idEuropean Medicines Agency (EMA)`)
    REFERENCES `mydb`.`Vaccines` (`idVaccines` , `Vaccine Producing Company_idVaccine Producing Company` , `European Medicines Agency (EMA)_idEuropean Medicines Agency (EMA)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccination` (
  `idVaccination` INT NOT NULL,
  `Patients Date of Birth` DATE NOT NULL,
  `Vaccination Detail` VARCHAR(45) NOT NULL,
  `Date of dose 1` DATE NOT NULL,
  `Date of dose 2` DATE NOT NULL,
  PRIMARY KEY (`Patients Date of Birth`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visit` (
  `idVisit` INT NOT NULL,
  `Patient_idPatiens` INT NOT NULL,
  `Date of Visit` VARCHAR(45) NOT NULL,
  `Patient_e-Government Center for Social Security (IDIKA)_AMKA` VARCHAR(45) NOT NULL,
  `Hospital_Name` VARCHAR(45) NOT NULL,
  `Medical Centers_idMedical Centers` INT NOT NULL,
  `Doctor_idDoctor` INT NOT NULL,
  `COVID-19 Test_Hospitalization_idHospitalization` INT NOT NULL,
  `COVID-19 Test_idCOVID-19 Test` INT NOT NULL,
  `COVID-19 Test_Hospitalization_COVID_idCOVID` INT NOT NULL,
  PRIMARY KEY (`idVisit`, `Patient_idPatiens`, `Patient_e-Government Center for Social Security (IDIKA)_AMKA`, `Hospital_Name`, `Medical Centers_idMedical Centers`),
  INDEX `fk_Visit_Patient1_idx` (`Patient_idPatiens` ASC, `Patient_e-Government Center for Social Security (IDIKA)_AMKA` ASC) VISIBLE,
  INDEX `fk_Visit_COVID-19 Test1_idx` (`COVID-19 Test_idCOVID-19 Test` ASC, `COVID-19 Test_Hospitalization_idHospitalization` ASC, `COVID-19 Test_Hospitalization_COVID_idCOVID` ASC) VISIBLE,
  INDEX `fk_Visit_Medical Centers1_idx` (`Medical Centers_idMedical Centers` ASC) VISIBLE,
  INDEX `fk_Visit_Hospital1_idx` (`Hospital_Name` ASC) VISIBLE,
  INDEX `fk_Visit_Doctor1_idx` (`Doctor_idDoctor` ASC) VISIBLE,
  CONSTRAINT `fk_Visit_Patient1`
    FOREIGN KEY (`Patient_idPatiens` , `Patient_e-Government Center for Social Security (IDIKA)_AMKA`)
    REFERENCES `mydb`.`Patient` (`idPatiens` , `e-Government Center for Social Security (IDIKA)_AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_COVID-19 Test1`
    FOREIGN KEY (`COVID-19 Test_idCOVID-19 Test` , `COVID-19 Test_Hospitalization_idHospitalization` , `COVID-19 Test_Hospitalization_COVID_idCOVID`)
    REFERENCES `mydb`.`COVID-19 Test` (`idCOVID-19 Test` , `Hospitalization_idHospitalization` , `Hospitalization_COVID_idCOVID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_Medical Centers1`
    FOREIGN KEY (`Medical Centers_idMedical Centers`)
    REFERENCES `mydb`.`Medical Centers` (`idMedical Centers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_Hospital1`
    FOREIGN KEY (`Hospital_Name`)
    REFERENCES `mydb`.`Hospital` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `mydb`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COVID_has_Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COVID_has_Room` (
  `COVID_idCOVID` INT NOT NULL,
  `Room_idRoom` INT NOT NULL,
  PRIMARY KEY (`COVID_idCOVID`, `Room_idRoom`),
  INDEX `fk_COVID_has_Room_Room1_idx` (`Room_idRoom` ASC) VISIBLE,
  INDEX `fk_COVID_has_Room_COVID1_idx` (`COVID_idCOVID` ASC) VISIBLE,
  CONSTRAINT `fk_COVID_has_Room_COVID1`
    FOREIGN KEY (`COVID_idCOVID`)
    REFERENCES `mydb`.`COVID Unit` (`idCOVID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COVID_has_Room_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `mydb`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Intensive Care Unit (ICU)_has_Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Intensive Care Unit (ICU)_has_Doctor` (
  `Intensive Care Unit (ICU)_idIntensive Care Unit (ICU)` INT NOT NULL,
  `Intensive Care Unit (ICU)_NO COVID_idNO COVID` INT NOT NULL,
  `Intensive Care Unit (ICU)_COVID_idCOVID` INT NOT NULL,
  `Intensive Care Unit (ICU)_Hospital_Name` VARCHAR(45) NOT NULL,
  `Doctor_idDoctor` INT NOT NULL,
  `Doctor_Hospital_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Intensive Care Unit (ICU)_idIntensive Care Unit (ICU)`, `Intensive Care Unit (ICU)_NO COVID_idNO COVID`, `Intensive Care Unit (ICU)_COVID_idCOVID`, `Intensive Care Unit (ICU)_Hospital_Name`, `Doctor_idDoctor`, `Doctor_Hospital_Name`),
  INDEX `fk_Intensive Care Unit (ICU)_has_Doctor_Doctor1_idx` (`Doctor_idDoctor` ASC, `Doctor_Hospital_Name` ASC) VISIBLE,
  INDEX `fk_Intensive Care Unit (ICU)_has_Doctor_Intensive Care Unit_idx` (`Intensive Care Unit (ICU)_idIntensive Care Unit (ICU)` ASC, `Intensive Care Unit (ICU)_NO COVID_idNO COVID` ASC, `Intensive Care Unit (ICU)_COVID_idCOVID` ASC, `Intensive Care Unit (ICU)_Hospital_Name` ASC) VISIBLE,
  CONSTRAINT `fk_Intensive Care Unit (ICU)_has_Doctor_Intensive Care Unit (1`
    FOREIGN KEY (`Intensive Care Unit (ICU)_idIntensive Care Unit (ICU)` , `Intensive Care Unit (ICU)_NO COVID_idNO COVID` , `Intensive Care Unit (ICU)_COVID_idCOVID` , `Intensive Care Unit (ICU)_Hospital_Name`)
    REFERENCES `mydb`.`Intensive Care Unit (ICU)` (`idIntensive Care Unit (ICU)` , `NO COVID_idNO COVID` , `COVID_idCOVID` , `Hospital_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Intensive Care Unit (ICU)_has_Doctor_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor` , `Doctor_Hospital_Name`)
    REFERENCES `mydb`.`Doctor` (`idDoctor` , `Hospital_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccine Center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccine Center` (
  `Hospital_Name` VARCHAR(45) NOT NULL,
  `Medical Centers_idMedical Centers` INT NOT NULL,
  PRIMARY KEY (`Hospital_Name`, `Medical Centers_idMedical Centers`),
  INDEX `fk_Vaccine Center_Medical Centers1_idx` (`Medical Centers_idMedical Centers` ASC) VISIBLE,
  CONSTRAINT `fk_Vaccine Center_Hospital1`
    FOREIGN KEY (`Hospital_Name`)
    REFERENCES `mydb`.`Hospital` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaccine Center_Medical Centers1`
    FOREIGN KEY (`Medical Centers_idMedical Centers`)
    REFERENCES `mydb`.`Medical Centers` (`idMedical Centers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Not Vaccine Center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Not Vaccine Center` (
  `Hospital_Name` VARCHAR(45) NOT NULL,
  `Medical Centers_idMedical Centers` INT NOT NULL,
  PRIMARY KEY (`Hospital_Name`, `Medical Centers_idMedical Centers`),
  INDEX `fk_Not Vaccine Center_Medical Centers1_idx` (`Medical Centers_idMedical Centers` ASC) VISIBLE,
  CONSTRAINT `fk_Not Vaccine Center_Hospital1`
    FOREIGN KEY (`Hospital_Name`)
    REFERENCES `mydb`.`Hospital` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Not Vaccine Center_Medical Centers1`
    FOREIGN KEY (`Medical Centers_idMedical Centers`)
    REFERENCES `mydb`.`Medical Centers` (`idMedical Centers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaccine Center_has_Vaccination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaccine Center_has_Vaccination` (
  `Vaccine Center_Hospital_Name` VARCHAR(45) NOT NULL,
  `Vaccine Center_Medical Centers_idMedical Centers` INT NOT NULL,
  `Vaccination_Patients Date of Birth` DATE NOT NULL,
  PRIMARY KEY (`Vaccine Center_Hospital_Name`, `Vaccine Center_Medical Centers_idMedical Centers`, `Vaccination_Patients Date of Birth`),
  INDEX `fk_Vaccine Center_has_Vaccination_Vaccination1_idx` (`Vaccination_Patients Date of Birth` ASC) VISIBLE,
  INDEX `fk_Vaccine Center_has_Vaccination_Vaccine Center1_idx` (`Vaccine Center_Hospital_Name` ASC, `Vaccine Center_Medical Centers_idMedical Centers` ASC) VISIBLE,
  CONSTRAINT `fk_Vaccine Center_has_Vaccination_Vaccine Center1`
    FOREIGN KEY (`Vaccine Center_Hospital_Name` , `Vaccine Center_Medical Centers_idMedical Centers`)
    REFERENCES `mydb`.`Vaccine Center` (`Hospital_Name` , `Medical Centers_idMedical Centers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaccine Center_has_Vaccination_Vaccination1`
    FOREIGN KEY (`Vaccination_Patients Date of Birth`)
    REFERENCES `mydb`.`Vaccination` (`Patients Date of Birth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
